### PR TITLE
fix: song placeholder icon in player view

### LINKED ISSUE #49: Missing thumbnail placeholder for local music
### Steps to reproduce

1. Play a local music file
2. Open the player
3. Observer the missing placeholder / blank space

### Expected behavior

Show a placeholder like in the music list.

### Actual behavior

No placeholder.

### Vibe You version

1.0

### Android version

A13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by SuhasDissa**
fix #49

### CODE REVIEW

File: app/src/main/java/app/suhasdissa/vibeyou/ui/screens/player/FullScreenPlayer.kt [hunk 1]
```diff
@@ -118,13 +118,24 @@ fun FullScreenPlayer(
...
-                        painter = rememberAsyncImagePainter(model = it.mediaMetadata.artworkUri),
+                val state1 = painter.state
+                if (state1 !is AsyncImagePainter.State.Success) {
+                    SubcomposeAsyncImage(
+                        model = it.mediaMetadata.artworkUri,
                         contentDescription,
                         contentScale = contentScale
-                    )
+                    ) {
+                        val state2 = painter.state
```
Comment (Bnyro) [inline app/src/main/java/app/suhasdissa/vibeyou/ui/screens/player/FullScreenPlayer.kt:128]: `state1` and `state2` would always be equal because they're reacting to changes to `painter.state` I think? And this looks way too nested to me, I'd prefer to make it simpler if possible.

Comment (SuhasDissa) [reply app/src/main/java/app/suhasdissa/vibeyou/ui/screens/player/FullScreenPlayer.kt:128]: No, the state1 is for the outer(high res) image
And the state2 is for the inner(low res) image

The `painter` os actually a member of the SubcomposeAsyncImageScope

This first tries to load the high res one, if it fails, this will try loading the low res image.
If all fails, this will fall back to the placeholder image.

Comment (Bnyro) [reply app/src/main/java/app/suhasdissa/vibeyou/ui/screens/player/FullScreenPlayer.kt:128]: Oh, I see ...
I thought the painter was introduced somewhere above.
Still, I'd prefer a solution with less nesting, e.g. if we had a boolean `val isError by remember { mutableStateOf(false) }` that we set to true if there's an error and then do
```kotlin
if (isError) {
   Image(//placeholder)
}
```
In the same if else statement, so that it's less nested and easier to read.

**Review by Bnyro — APPROVED** [review]
